sonar.projectKey=limit
sonar.projectName=Limit
sonar.sources=backend/src/main/java
sonar.tests=backend/src/test
sonar.java.binaries=backend/build/classes
sonar.coverage.jacoco.xmlReportPaths=backend/build/reports/jacoco/test/jacocoTestReport.xml
sonar.exclusions=backend/build/**
