FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
RUN apk upgrade --no-cache \
    && addgroup -S spring \
    && adduser -S spring -G spring
COPY build/libs/app.jar app.jar

USER spring:spring
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
