global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'sungwoo515@gmail.com'          # .env의 MAIL_FROM과 동일하게 채우기
  smtp_auth_username: 'sungwoo515@gmail.com' # .env의 MAIL_USERNAME과 동일하게 채우기
  smtp_auth_password_file: /run/secrets/alertmanager-smtp-password
  smtp_require_tls: true

route:
  receiver: email-sungwoo
  group_by: [alertname, severity]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: email-sungwoo
    email_configs:
      - to: 'sungwoo515@gmail.com'
        send_resolved: true
