server {
    listen 80;
    listen [::]:80;
    server_name api.l1mit.shop admin.l1mit.shop docs.l1mit.shop grafana.l1mit.shop;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/limit-certbot;
        default_type text/plain;
    }

    location / {
        return 308 https://$host$request_uri;
    }
}
