package com.c203.limit.domain.admin.service;
import java.time.*;import java.util.*;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.c203.limit.domain.admin.entity.MemberRoleAssignment;import com.c203.limit.domain.admin.repository.*;import com.c203.limit.domain.inquiry.entity.*;import com.c203.limit.domain.inquiry.repository.*;import com.c203.limit.domain.member.repository.MemberRepository;import com.c203.limit.domain.seller.client.SellerDocumentStorage;import com.c203.limit.domain.seller.repository.SellerApplicationDocumentRepository;import com.c203.limit.domain.withdrawal.entity.WithdrawalRequest;import com.c203.limit.domain.withdrawal.repository.WithdrawalRequestRepository;import com.c203.limit.global.exception.*;import com.c203.limit.global.response.PageResponse;
@Service public class AdminSupportService{
 private final WithdrawalRequestRepository withdrawals;private final InquiryRepository inquiries;private final InquiryAnswerRepository answers;private final MemberRoleAssignmentRepository roles;private final MemberRepository members;private final AdminActionLogRepository logs;private final SellerApplicationDocumentRepository documents;private final Optional<SellerDocumentStorage> storage;
 public AdminSupportService(WithdrawalRequestRepository w,InquiryRepository i,InquiryAnswerRepository a,MemberRoleAssignmentRepository r,MemberRepository m,AdminActionLogRepository l,SellerApplicationDocumentRepository d,Optional<SellerDocumentStorage>s){withdrawals=w;inquiries=i;answers=a;roles=r;members=m;logs=l;documents=d;storage=s;}
 @Transactional(readOnly=true)public PageResponse<Map<String,Object>> withdrawals(Integer p,Integer s){var result=withdrawals.findAll(pageable(p,s));return page(result,result.stream().map(this::withdrawal).toList());}
 @Transactional(readOnly=true)public Map<String,Object> withdrawal(Long id){return withdrawal(getWithdrawal(id));}
 @Transactional public Map<String,Object> processWithdrawal(Long admin,Long id,String decision,String reason){var w=getWithdrawal(id);w.process(admin,decision,reason);audit(admin,"WITHDRAWAL_PROCESS","WITHDRAWAL",id,reason);return map("withdrawalRequestId",id,"status",w.getStatus(),"processedBy",admin,"processedAt",w.getProcessedAt());}
 @Transactional(readOnly=true)public PageResponse<Map<String,Object>> inquiries(Integer p,Integer s){var result=inquiries.findAll(pageable(p,s));return page(result,result.stream().map(this::inquirySummary).toList());}
 @Transactional(readOnly=true)public Map<String,Object> inquiry(Long id){var q=getInquiry(id);return map("inquiryId",id,"member",map("memberId",q.getMember().getId(),"email",mask(q.getMember().getEmail())),"category",q.getCategory(),"title",q.getTitle(),"content",q.getContent(),"status",q.getStatus(),"answers",answers.findAllByInquiryIdOrderByVersionAsc(id).stream().map(this::answer).toList());}
 @Transactional public Map<String,Object> answer(Long admin,Long id,String content){if(content==null||content.isBlank())throw new BusinessException(ErrorCode.INVALID_INPUT_VALUE);var q=getInquiry(id);var old=answers.findAllByInquiryIdOrderByVersionAsc(id);old.stream().filter(InquiryAnswer::isCurrent).forEach(InquiryAnswer::supersede);var a=answers.save(InquiryAnswer.create(q,old.size()+1,content,admin));q.answered();audit(admin,"INQUIRY_ANSWER","INQUIRY",id,null);return answer(a);}
 @Transactional public Map<String,Object> inquiryStatus(Long admin,Long id,String status){var q=getInquiry(id);q.changeStatus(status);audit(admin,"INQUIRY_STATUS_CHANGE","INQUIRY",id,status);return map("inquiryId",id,"status",status,"closedAt",q.getClosedAt());}
 @Transactional(readOnly=true)public List<Map<String,Object>> roleList(){return List.of(map("roleId",1L,"roleCode","BUYER","roleName","구매자"),map("roleId",2L,"roleCode","SELLER","roleName","판매자"),map("roleId",3L,"roleCode","OPERATOR","roleName","운영 관리자"),map("roleId",4L,"roleCode","SUPER_ADMIN","roleName","최고 관리자"));}
 @Transactional public Map<String,Object> grantRole(Long admin,Long memberId,String role,String reason){members.findById(memberId).orElseThrow(()->new BusinessException(ErrorCode.MEMBER_NOT_FOUND));if(!Set.of("BUYER","SELLER","OPERATOR","SUPER_ADMIN").contains(role)||roles.existsByMemberIdAndRoleCode(memberId,role))throw new BusinessException(ErrorCode.INVALID_INPUT_VALUE);var a=roles.save(MemberRoleAssignment.grant(memberId,role,admin));audit(admin,"ROLE_GRANT","MEMBER",memberId,reason);return map("memberRoleId",a.getId(),"memberId",memberId,"roleCode",role,"grantedAt",a.getGrantedAt());}
 @Transactional public void revokeRole(Long admin,Long memberId,Long roleId){var role=roles.findById(roleId).orElseThrow(()->new BusinessException(ErrorCode.INVALID_INPUT_VALUE));if(!role.getMemberId().equals(memberId))throw new BusinessException(ErrorCode.FORBIDDEN);roles.delete(role);audit(admin,"ROLE_REVOKE","MEMBER",memberId,role.getRoleCode());}
 @Transactional(readOnly=true)public Map<String,Object> presign(Long admin,Long documentId,int seconds){var d=documents.findById(documentId).orElseThrow(()->new BusinessException(ErrorCode.SELLER_DOCUMENT_NOT_FOUND));var store=storage.orElseThrow(()->new BusinessException(ErrorCode.INVALID_INPUT_VALUE,"S3 저장소 구현이 구성되지 않았습니다."));int ttl=Math.min(300,Math.max(1,seconds));String url=store.createDownloadUrl(d.getStorageKey(),Duration.ofSeconds(ttl));return map("documentId",documentId,"downloadUrl",url,"expiresAt",OffsetDateTime.now().plusSeconds(ttl));}
 private WithdrawalRequest getWithdrawal(Long id){return withdrawals.findById(id).orElseThrow(()->new BusinessException(ErrorCode.WITHDRAWAL_REQUEST_NOT_FOUND));}private Inquiry getInquiry(Long id){return inquiries.findById(id).orElseThrow(()->new BusinessException(ErrorCode.INQUIRY_NOT_FOUND));}
 private Map<String,Object> withdrawal(WithdrawalRequest w){return map("withdrawalRequestId",w.getId(),"memberId",w.getMember().getId(),"memberEmail",mask(w.getMember().getEmail()),"status",w.getStatus(),"withdrawalReason",w.getReason(),"blockedReason",w.getBlockedReason(),"requestedAt",w.getRequestedAt(),"processedAt",w.getProcessedAt());}private Map<String,Object> inquirySummary(Inquiry q){return map("inquiryId",q.getId(),"memberId",q.getMember().getId(),"memberEmail",mask(q.getMember().getEmail()),"category",q.getCategory(),"title",q.getTitle(),"status",q.getStatus(),"createdAt",q.getCreatedAt());}private Map<String,Object> answer(InquiryAnswer a){return map("answerId",a.getId(),"inquiryId",a.getInquiry().getId(),"version",a.getVersion(),"content",a.getContent(),"isCurrent",a.isCurrent(),"adminId",a.getAdminId(),"createdAt",a.getCreatedAt());}
 private void audit(Long a,String action,String target,Long id,String reason){logs.save(com.c203.limit.domain.admin.entity.AdminActionLog.of(a,action,target,id,reason));}private Pageable pageable(Integer p,Integer s){return PageRequest.of(p==null?0:Math.max(0,p),s==null?20:Math.min(100,Math.max(1,s)));}private <T>PageResponse<T> page(Page<?>p,List<T>c){return new PageResponse<>(c,p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages(),p.hasNext());}private String mask(String e){if(e==null)return null;int at=e.indexOf('@');return at<1?"***":e.substring(0,1)+"***"+e.substring(at);}private Map<String,Object>map(Object...v){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<v.length;i+=2)m.put((String)v[i],v[i+1]);return m;}
}
