package com.c203.limit.domain.admin.service;
import java.math.BigDecimal; import java.time.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.c203.limit.domain.admin.entity.*; import com.c203.limit.domain.admin.repository.*; import com.c203.limit.domain.auth.service.RefreshTokenStore; import com.c203.limit.domain.member.entity.Member; import com.c203.limit.domain.member.repository.MemberRepository; import com.c203.limit.domain.seller.entity.*; import com.c203.limit.domain.seller.repository.*; import com.c203.limit.global.exception.*; import com.c203.limit.global.response.PageResponse; import com.c203.limit.global.security.JwtTokenProvider;
@Service public class AdminService{
 private final AdminAccountRepository admins;private final MemberRepository members;private final MemberRestrictionRepository restrictions;private final AdminActionLogRepository logs;private final SellerApplicationRepository applications;private final SellerApplicationDocumentRepository documents;private final SellerRepository sellers;private final PasswordEncoder encoder;private final JwtTokenProvider tokens;private final RefreshTokenStore refreshStore;
 public AdminService(AdminAccountRepository admins,MemberRepository members,MemberRestrictionRepository restrictions,AdminActionLogRepository logs,SellerApplicationRepository applications,SellerApplicationDocumentRepository documents,SellerRepository sellers,PasswordEncoder encoder,JwtTokenProvider tokens,RefreshTokenStore refreshStore){this.admins=admins;this.members=members;this.restrictions=restrictions;this.logs=logs;this.applications=applications;this.documents=documents;this.sellers=sellers;this.encoder=encoder;this.tokens=tokens;this.refreshStore=refreshStore;}
 @Transactional(readOnly=true) public Map<String,Object> login(String email,String password){var a=admins.findByEmailIgnoreCase(email).orElseThrow(()->new BusinessException(ErrorCode.INVALID_CREDENTIALS));if(!"ACTIVE".equals(a.getStatus())||!encoder.matches(password,a.getPassword()))throw new BusinessException(ErrorCode.INVALID_CREDENTIALS);var roles=Set.of(a.getRole());var access=tokens.issueAccess(a.getId(),"ADMIN",roles);var refresh=tokens.issueRefresh(a.getId(),"ADMIN",roles);refreshStore.save(refresh.tokenId(),a.getId(),tokens.refreshTtl());return map("accessToken",access.value(),"refreshToken",refresh.value(),"tokenType","Bearer","expiresIn",tokens.accessTtl().toSeconds(),"admin",map("adminId",a.getId(),"name",a.getName(),"roles",roles));}
 @Transactional(readOnly=true) public PageResponse<Map<String,Object>> members(Integer page,Integer size){var p=page(page,size);var result=members.findAll(p);return page(result,result.stream().map(this::memberSummary).toList());}
 @Transactional(readOnly=true) public Map<String,Object> member(Long id){return memberSummary(getMember(id));}
 @Transactional(readOnly=true) public PageResponse<Map<String,Object>> restrictions(Long memberId,Integer page,Integer size){getMember(memberId);var result=restrictions.findAllByMemberId(memberId,page(page,size));return page(result,result.stream().map(this::restrictionMap).toList());}
 @Transactional public Map<String,Object> restrict(Long adminId,Long memberId,String type,String code,String detail,OffsetDateTime starts,OffsetDateTime ends){var member=getMember(memberId);if(restrictions.existsByMemberIdAndTypeAndStatus(memberId,type,"ACTIVE"))throw new BusinessException(ErrorCode.OVERLAPPING_RESTRICTION);var r=restrictions.save(MemberRestriction.create(member,type,code,detail,starts,ends,adminId));audit(adminId,"MEMBER_RESTRICT","MEMBER",memberId,detail);return restrictionMap(r);}
 @Transactional public Map<String,Object> release(Long adminId,Long restrictionId,String reason){var r=restrictions.findById(restrictionId).orElseThrow(()->new BusinessException(ErrorCode.MEMBER_RESTRICTION_NOT_FOUND));r.release(adminId,reason);audit(adminId,"MEMBER_RESTRICTION_RELEASE","MEMBER",r.getMember().getId(),reason);return restrictionMap(r);}
 @Transactional(readOnly=true) public PageResponse<Map<String,Object>> applications(Integer page,Integer size){var result=applications.findAll(page(page,size));return page(result,result.stream().map(this::applicationSummary).toList());}
 @Transactional(readOnly=true) public Map<String,Object> application(Long id){var a=getApplication(id);return map("applicationId",a.getId(),"memberId",a.getMember().getId(),"applicationVersion",a.getVersion(),"sellerType",a.getType().name(),"status",a.getStatus().name(),"applicantName",a.getApplicantName(),"applicantEmail",maskEmail(a.getApplicantEmail()),"applicantPhone",maskPhone(a.getApplicantPhone()),"countryCode",a.getCountryCode(),"businessName",a.getBusinessName(),"plannedCategory",a.getPlannedCategory(),"documents",documents.findAllByApplicationId(id).stream().map(d->map("documentId",d.getId(),"documentType",d.getDocumentType(),"originalFilename",d.getOriginalFilename())).toList(),"submittedAt",a.getSubmittedAt());}
 @Transactional public Map<String,Object> startReview(Long adminId,Long id){var a=getApplication(id);a.startReview(adminId);audit(adminId,"SELLER_REVIEW_START","SELLER_APPLICATION",id,null);return map("applicationId",id,"status",a.getStatus().name(),"reviewerAdminId",adminId,"updatedAt",a.getUpdatedAt());}
 @Transactional public Map<String,Object> approve(Long adminId,Long id){var a=getApplication(id);if(sellers.existsByMemberId(a.getMember().getId()))throw new BusinessException(ErrorCode.ALREADY_SELLER);a.approve(adminId);var seller=sellers.save(Seller.approve(a));a.getMember().grantSellerRole();audit(adminId,"SELLER_APPROVE","SELLER_APPLICATION",id,null);return map("applicationId",id,"status","APPROVED","sellerProfileId",seller.getId(),"memberId",a.getMember().getId(),"sellerStatus",seller.getStatus(),"reviewedAt",a.getReviewedAt());}
 @Transactional public Map<String,Object> reject(Long adminId,Long id,String reason){var a=getApplication(id);a.reject(adminId,reason);audit(adminId,"SELLER_REJECT","SELLER_APPLICATION",id,reason);return map("applicationId",id,"status","REJECTED","rejectionReason",reason,"reviewedAt",a.getReviewedAt());}
 @Transactional(readOnly=true) public PageResponse<Map<String,Object>> sellers(Integer page,Integer size){var result=sellers.findAll(page(page,size));return page(result,result.stream().map(this::sellerMap).toList());}
 @Transactional(readOnly=true) public Map<String,Object> seller(Long id){return sellerMap(sellers.findById(id).orElseThrow(()->new BusinessException(ErrorCode.SELLER_PROFILE_NOT_FOUND)));}
 @Transactional public Map<String,Object> sellerStatus(Long adminId,Long id,String status,String reason){var s=sellers.findById(id).orElseThrow(()->new BusinessException(ErrorCode.SELLER_PROFILE_NOT_FOUND));if(!Set.of("ACTIVE","SELLING_RESTRICTED","SUSPENDED","TERMINATED").contains(status))throw new BusinessException(ErrorCode.INVALID_INPUT_VALUE);s.updateStatus(status);audit(adminId,"SELLER_STATUS_CHANGE","SELLER",id,reason);return map("sellerProfileId",id,"sellerStatus",status,"updatedAt",OffsetDateTime.now());}
 @Transactional public Map<String,Object> sellerLimits(Long adminId,Long id,int productLimit,BigDecimal salesLimit,String reason){var s=sellers.findById(id).orElseThrow(()->new BusinessException(ErrorCode.SELLER_PROFILE_NOT_FOUND));s.updateLimits(productLimit,salesLimit);audit(adminId,"SELLER_LIMIT_CHANGE","SELLER",id,reason);return map("sellerProfileId",id,"productLimit",productLimit,"salesAmountLimit",salesLimit,"updatedAt",OffsetDateTime.now());}
 @Transactional(readOnly=true) public PageResponse<Map<String,Object>> logs(Integer page,Integer size){var result=logs.findAll(PageRequest.of(page==null?0:Math.max(0,page),size==null?20:Math.min(100,Math.max(1,size)),Sort.by(Sort.Direction.DESC,"createdAt")));return page(result,result.stream().map(this::logMap).toList());}
 @Transactional(readOnly=true) public Map<String,Object> log(Long id){return logMap(logs.findById(id).orElseThrow(()->new BusinessException(ErrorCode.ADMIN_ACTION_LOG_NOT_FOUND)));}
 private void audit(Long admin,String action,String target,Long id,String reason){logs.save(AdminActionLog.of(admin,action,target,id,reason));}
 private Member getMember(Long id){return members.findById(id).orElseThrow(()->new BusinessException(ErrorCode.MEMBER_NOT_FOUND));} private SellerApplication getApplication(Long id){return applications.findById(id).orElseThrow(()->new BusinessException(ErrorCode.SELLER_APPLICATION_NOT_FOUND));}
 private Map<String,Object> memberSummary(Member m){return map("memberId",m.getId(),"email",maskEmail(m.getEmail()),"nickname",m.getNickname(),"phone",maskPhone(m.getPhone()),"status",m.getStatus().name(),"authType",m.getPassword()==null?"SOCIAL":"LOCAL","roles",Set.of(m.getRole().name()),"activeRestrictionCount",restrictions.countByMemberIdAndStatus(m.getId(),"ACTIVE"),"createdAt",m.getCreatedAt());}
 private Map<String,Object> restrictionMap(MemberRestriction r){return map("restrictionId",r.getId(),"memberId",r.getMember().getId(),"restrictionType",r.getType(),"status",r.getStatus(),"reasonCode",r.getReasonCode(),"reasonDetail",r.getReasonDetail(),"startsAt",r.getStartsAt(),"endsAt",r.getEndsAt(),"createdBy",r.getCreatedBy(),"releasedBy",r.getReleasedBy(),"releasedAt",r.getReleasedAt(),"releaseReason",r.getReleaseReason(),"createdAt",r.getCreatedAt());}
 private Map<String,Object> applicationSummary(SellerApplication a){return map("applicationId",a.getId(),"memberId",a.getMember().getId(),"applicantEmail",maskEmail(a.getApplicantEmail()),"sellerType",a.getType().name(),"countryCode",a.getCountryCode(),"status",a.getStatus().name(),"applicationVersion",a.getVersion(),"submittedAt",a.getSubmittedAt());}
 private Map<String,Object> sellerMap(Seller s){return map("sellerProfileId",s.getId(),"memberId",s.getMember().getId(),"memberEmail",maskEmail(s.getMember().getEmail()),"businessName",s.getBusinessName(),"sellerType",s.getType().name(),"sellerStatus",s.getStatus(),"countryCode",s.getCountryCode(),"productLimit",s.getProductLimit(),"salesAmountLimit",s.getSalesAmountLimit(),"approvedAt",s.getApprovedAt());}
 private Map<String,Object> logMap(AdminActionLog l){return map("adminActionLogId",l.getId(),"adminId",l.getAdminId(),"actionType",l.getActionType(),"targetType",l.getTargetType(),"targetId",l.getTargetId(),"reason",l.getReason(),"beforeData",l.getBeforeData(),"afterData",l.getAfterData(),"ipAddress",l.getIpAddress(),"createdAt",l.getCreatedAt());}
 private PageRequest page(Integer p,Integer s){return PageRequest.of(p==null?0:Math.max(0,p),s==null?20:Math.min(100,Math.max(1,s)));} private <T> PageResponse<T> page(Page<?> p,List<T> c){return new PageResponse<>(c,p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages(),p.hasNext());}
 private String maskEmail(String e){if(e==null)return null;int at=e.indexOf('@');return at<1?"***":e.substring(0,1)+"***"+e.substring(at);} private String maskPhone(String p){return p==null||p.length()<7?p:p.substring(0,3)+"****"+p.substring(p.length()-4);}
 private Map<String,Object> map(Object... values){Map<String,Object> m=new LinkedHashMap<>();for(int i=0;i<values.length;i+=2)m.put((String)values[i],values[i+1]);return m;}
}
