package com.c203.limit.domain.seller.service;
import java.util.*; import org.springframework.data.domain.PageRequest; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile;
import com.c203.limit.domain.member.repository.MemberRepository; import com.c203.limit.domain.seller.client.SellerDocumentStorage; import com.c203.limit.domain.seller.dto.request.UpdateSellerApplicationRequest; import com.c203.limit.domain.seller.dto.response.*; import com.c203.limit.domain.seller.entity.*; import com.c203.limit.domain.seller.repository.*; import com.c203.limit.global.exception.*; import com.c203.limit.global.response.PageResponse;
@Service public class SellerService {
 private final SellerApplicationRepository applications; private final SellerApplicationDocumentRepository documents; private final SellerRepository sellers; private final MemberRepository members; private final Optional<SellerDocumentStorage> storage;
 public SellerService(SellerApplicationRepository a,SellerApplicationDocumentRepository d,SellerRepository s,MemberRepository m,Optional<SellerDocumentStorage> storage){applications=a;documents=d;sellers=s;members=m;this.storage=storage;}
 @Transactional public SellerApplicationSummaryResponse create(Long memberId,String typeValue){if(sellers.existsByMemberId(memberId))throw new BusinessException(ErrorCode.ALREADY_SELLER);if(applications.existsByMemberIdAndStatusIn(memberId,List.of(SellerApplicationStatus.DRAFT,SellerApplicationStatus.SUBMITTED,SellerApplicationStatus.UNDER_REVIEW)))throw new BusinessException(ErrorCode.ACTIVE_SELLER_APPLICATION_EXISTS);SellerType type;try{type=SellerType.valueOf(typeValue);}catch(Exception e){throw new BusinessException(ErrorCode.INVALID_INPUT_VALUE);}var member=members.findById(memberId).orElseThrow(()->new BusinessException(ErrorCode.MEMBER_NOT_FOUND));var a=applications.save(SellerApplication.draft(member,(int)applications.countByMemberId(memberId)+1,type));return summary(a);}
 @Transactional(readOnly=true) public PageResponse<SellerApplicationSummaryResponse> list(Long memberId,Integer page,Integer size){int p=page==null?0:Math.max(0,page),s=size==null?20:Math.min(100,Math.max(1,size));var result=applications.findAllByMemberId(memberId,PageRequest.of(p,s));return new PageResponse<>(result.map(this::summary).getContent(),p,s,result.getTotalElements(),result.getTotalPages(),result.hasNext());}
 @Transactional(readOnly=true) public SellerApplicationDetailResponse detail(Long memberId,Long id){var a=getOwned(memberId,id);var docs=documents.findAllByApplicationId(id).stream().map(this::documentResponse).toList();return new SellerApplicationDetailResponse(a.getId(),a.getVersion(),a.getType().name(),a.getStatus().name(),a.getApplicantName(),a.getApplicantEmail(),maskPhone(a.getApplicantPhone()),a.getCountryCode(),a.getBusinessName(),a.getPlannedCategory(),docs,a.getRejectionReason(),a.getSubmittedAt(),a.getReviewedAt(),a.getCreatedAt(),a.getUpdatedAt());}
 @Transactional public SellerApplicationStatusResponse update(Long memberId,Long id,UpdateSellerApplicationRequest r){var a=getOwned(memberId,id);a.update(r.getApplicantName(),r.getApplicantEmail(),r.getApplicantPhone(),r.getCountryCode(),r.getBusinessName(),r.getBusinessNumber(),r.getBusinessAddress(),r.getSettlementBankName(),r.getSettlementAccount(),r.getSettlementAccountHolder(),r.getPlannedCategory(),r.isTermsAgreed());return status(a);}
 @Transactional public List<SellerApplicationDocumentResponse> upload(Long memberId,Long id,MultipartFile[] files){var a=getOwned(memberId,id);a.requireEditable();if(storage.isEmpty())throw new BusinessException(ErrorCode.INVALID_SELLER_DOCUMENT,"S3 저장소 구현이 구성되지 않았습니다.");if(files==null||files.length==0)throw new BusinessException(ErrorCode.INVALID_SELLER_DOCUMENT);List<SellerApplicationDocumentResponse> result=new ArrayList<>();for(var f:files){validate(f);String key=storage.get().upload(id,f);var d=documents.save(SellerApplicationDocument.create(a,"OTHER",key,cleanName(f.getOriginalFilename()),f.getContentType(),f.getSize()));result.add(documentResponse(d));}return result;}
 @Transactional public void deleteDocument(Long memberId,Long applicationId,Long documentId){var a=getOwned(memberId,applicationId);a.requireEditable();var d=documents.findByIdAndApplicationId(documentId,applicationId).orElseThrow(()->new BusinessException(ErrorCode.SELLER_DOCUMENT_NOT_FOUND));storage.ifPresent(s->s.delete(d.getStorageKey()));documents.delete(d);}
 @Transactional public SellerApplicationStatusResponse submit(Long memberId,Long id){var a=getOwned(memberId,id);a.submit(documents.existsByApplicationId(id));return status(a);}
 @Transactional public SellerApplicationStatusResponse cancel(Long memberId,Long id){var a=getOwned(memberId,id);a.cancel();return status(a);}
 @Transactional(readOnly=true) public SellerProfileResponse profile(Long memberId){var s=sellers.findByMemberId(memberId).orElseThrow(()->new BusinessException(ErrorCode.SELLER_PROFILE_NOT_FOUND));return new SellerProfileResponse(s.getId(),memberId,s.getType().name(),s.getStatus(),s.getCountryCode(),s.getBusinessName(),s.getProductLimit(),s.getSalesAmountLimit(),s.getApprovedAt());}
 private SellerApplication getOwned(Long memberId,Long id){return applications.findByIdAndMemberId(id,memberId).orElseThrow(()->new BusinessException(ErrorCode.SELLER_APPLICATION_NOT_FOUND));}
 private SellerApplicationSummaryResponse summary(SellerApplication a){return new SellerApplicationSummaryResponse(a.getId(),a.getVersion(),a.getType().name(),a.getStatus().name(),a.getSubmittedAt(),a.getReviewedAt());}
 private SellerApplicationStatusResponse status(SellerApplication a){return new SellerApplicationStatusResponse(a.getId(),a.getStatus().name(),a.getSubmittedAt(),a.getUpdatedAt());}
 private SellerApplicationDocumentResponse documentResponse(SellerApplicationDocument d){return new SellerApplicationDocumentResponse(d.getId(),d.getApplication().getId(),d.getDocumentType(),d.getOriginalFilename(),d.getContentType(),d.getFileSize(),d.getUploadedAt());}
 private void validate(MultipartFile f){if(f==null||f.isEmpty()||f.getSize()>10*1024*1024L||!Set.of("application/pdf","image/jpeg","image/png").contains(f.getContentType()))throw new BusinessException(ErrorCode.INVALID_SELLER_DOCUMENT);}
 private String cleanName(String n){if(n==null)return "document";return n.replace('\\','/').substring(n.replace('\\','/').lastIndexOf('/')+1);}
 private String maskPhone(String p){return p==null||p.length()<7?p:p.substring(0,Math.min(5,p.length()-4))+"****"+p.substring(p.length()-4);}
}
