package com.c203.limit.domain.admin.controller;
import java.math.BigDecimal;import java.time.*;import org.springframework.http.ResponseEntity;import org.springframework.web.bind.annotation.RestController;import com.c203.limit.domain.admin.service.*;import com.c203.limit.global.exception.*;import com.c203.limit.global.response.ApiResponse;import com.c203.limit.global.security.CurrentUser;import com.fasterxml.jackson.databind.*;
@RestController public class AdminController implements AdminApi{
 private final AdminService service;private final AdminSupportService support;private final AdminSearchService search;private final CurrentUser current;private final ObjectMapper mapper;public AdminController(AdminService s,AdminSupportService x,AdminSearchService search,CurrentUser c,ObjectMapper m){service=s;support=x;this.search=search;current=c;mapper=m;}
 public ResponseEntity<Void> adminauth01(Object b){var j=json(b);return ok(service.login(req(j,"email"),req(j,"password")));}public ResponseEntity<Void> adminmember01(Integer p,Integer s,String e,String n,String status,String role,LocalDate f,LocalDate t){return ok(search.members(p,s,e,n,status,role,f,t));}public ResponseEntity<Void> adminmember02(Long id){return ok(service.member(id));}public ResponseEntity<Void> adminmember03(Long id,Integer p,Integer s,String status){return ok(service.restrictions(id,p,s));}public ResponseEntity<Void> adminmember04(Long id,Object b){var j=json(b);return created(service.restrict(current.adminId(),id,req(j,"restrictionType"),req(j,"reasonCode"),req(j,"reasonDetail"),OffsetDateTime.parse(req(j,"startsAt")),OffsetDateTime.parse(req(j,"endsAt"))));}public ResponseEntity<Void> adminmember05(Long id,Object b){return ok(service.release(current.adminId(),id,req(json(b),"releaseReason")));}
 public ResponseEntity<Void> adminwithdrawal01(Integer p,Integer s,String status,String f,String t){return ok(search.withdrawals(p,s,status,f,t));}public ResponseEntity<Void> adminwithdrawal02(Long id){return ok(support.withdrawal(id));}public ResponseEntity<Void> adminwithdrawal03(Long id,Object b){var j=json(b);return ok(support.processWithdrawal(current.adminId(),id,req(j,"decision"),opt(j,"blockedReason")));}
 public ResponseEntity<Void> adminsellerapp01(Integer p,Integer s,String status,String type,String country,String f,String t){return ok(search.applications(p,s,status,type,country,f,t));}public ResponseEntity<Void> adminsellerapp02(Long id){return ok(service.application(id));}public ResponseEntity<Void> adminsellerapp03(Long id,String expires){return ok(support.presign(current.adminId(),id,expires==null?300:Integer.parseInt(expires)));}public ResponseEntity<Void> adminsellerapp04(Long id){return ok(service.startReview(current.adminId(),id));}public ResponseEntity<Void> adminsellerapp05(Long id,Object b){var j=json(b);return ok(service.approve(current.adminId(),id,j.path("productLimit").asInt(10),new BigDecimal(req(j,"salesAmountLimit"))));}public ResponseEntity<Void> adminsellerapp06(Long id,Object b){return ok(service.reject(current.adminId(),id,req(json(b),"rejectionReason")));}
 public ResponseEntity<Void> adminseller01(Integer p,Integer s,String status,String type,String country,String keyword){return ok(search.sellers(p,s,status,type,country,keyword));}public ResponseEntity<Void> adminseller02(Long id){return ok(service.seller(id));}public ResponseEntity<Void> adminseller03(Long id,Object b){var j=json(b);return ok(service.sellerStatus(current.adminId(),id,req(j,"sellerStatus"),opt(j,"reason")));}public ResponseEntity<Void> adminseller04(Long id,Object b){var j=json(b);return ok(service.sellerLimits(current.adminId(),id,j.path("productLimit").asInt(-1),new BigDecimal(req(j,"salesAmountLimit")),req(j,"reason")));}
 public ResponseEntity<Void> admininquiry01(Integer p,Integer s,String status,String category,Long memberId,LocalDate f,LocalDate t){return ok(search.inquiries(p,s,status,category,memberId,f,t));}public ResponseEntity<Void> admininquiry02(Long id){return ok(support.inquiry(id));}public ResponseEntity<Void> admininquiry03(Long id,Object b){return ok(support.answer(current.adminId(),id,req(json(b),"content")));}public ResponseEntity<Void> admininquiry04(Long id,Object b){return ok(support.inquiryStatus(current.adminId(),id,req(json(b),"status")));}
 public ResponseEntity<Void> adminrole01(){return ok(support.roleList());}public ResponseEntity<Void> adminrole02(Long id,Object b){var j=json(b);return created(support.grantRole(current.adminId(),id,req(j,"roleCode"),opt(j,"reason")));}public ResponseEntity<Void> adminrole03(Long id,Long roleId){support.revokeRole(current.adminId(),id,roleId);return ResponseEntity.noContent().build();}public ResponseEntity<Void> adminlog01(Integer p,Integer s,Long admin,String action,String target,Long targetId,LocalDate f,LocalDate t){return ok(search.logs(p,s,admin,action,target,targetId,f,t));}public ResponseEntity<Void> adminlog02(Long id){return ok(service.log(id));}
 private JsonNode json(Object b){if(b==null)throw new BusinessException(ErrorCode.INVALID_INPUT_VALUE);return mapper.valueToTree(b);}private String req(JsonNode j,String f){String v=opt(j,f);if(v==null||v.isBlank())throw new BusinessException(ErrorCode.INVALID_INPUT_VALUE);return v;}private String opt(JsonNode j,String f){var v=j.get(f);return v==null||v.isNull()?null:v.asText();}private ResponseEntity<Void> ok(Object d){return response(ResponseEntity.ok(ApiResponse.ok(d)));}private ResponseEntity<Void> created(Object d){return response(ResponseEntity.status(201).body(ApiResponse.ok(d)));}@SuppressWarnings({"rawtypes","unchecked"})private ResponseEntity<Void> response(ResponseEntity<?>r){return(ResponseEntity)r;}
}
